class Bab

  extend Babushka::ShellHelpers
  extend Babushka::RunHelpers

  def self.babushka_root
    @babushka_root ||= "#{File.dirname(__FILE__)}/.."
  end

  def self.generated_config?(path)
    path.p.grep(/Generated by babushka/)
  end

  def self.service_restart(service)
    shell "/etc/init.d/#{service} restart"
  end
end