def system_users
  ['philip']
end

def site_hostname
  'ivercore.com'
end

def root_mail_forwarder
  'philip@ivercore.com'
end

def group_email_address
  'philip@ivercore.com'
end

def babushka_root
  @babushka_root ||= "#{File.dirname(__FILE__)}/.."
end

def generated_config?(path)
  path.p.grep(/Generated by babushka/)
end

def run_expects(file_name)
  shell "#{babushka_root}/expects/#{file_name}"
end

def service_restart(service)
  shell "/etc/init.d/#{service} restart"
end