def system_users
  ['suitepad','philip']
end

def babushka_root
  @babushka_root ||= "#{File.dirname(__FILE__)}/.."
end

def generated_config?(path)
  path.p.grep(/Generated by babushka/)
end

def run_expects(file_name)
  shell "#{babushka_root}/expects/#{file_name}"
end

def service_restart(service)
  shell "/etc/init.d/#{service} restart"
end