dep 'ronaldo server' do
  requires 'sudo.managed',
    "user create".with(:user => 'philip'),
    "user bashify".with(:user => 'root', :home_base => ''),
    "user bashify".with(:user => 'philip', :home_base => '/home'),
    'curl',
    'grep',
    'tmux',
    'htop',
    'rsync',
    'ack',
    'git',
    'ruby',
    'passenger gem',
    'nginx',
    'java',
    'imagemagick',
    'libxml2',
    'libxslt',
    'iptables config',
    'postfix',
    'forward email'.with(:user_dir => '/root', :email => 'philip@ivercore.com')
    'sshd configure'.with(:allowed_users => 'philip git'),
    'backup',
end
